set(HPP_PATH
    include/controllers/NetworkScanningControllers.hpp
    include/tools/drawAppIcon.hpp
    include/controllers/PingControllers.hpp
    include/models/NetworkScanningModel.hpp
    include/models/PingModel.hpp
    include/tools/getLocalNetmask.hpp
    include/tools/getLocalIPAddress.hpp
)

set(CPP_PATH
    src/controllers/NetworkScanningControllers.cpp
    src/main.cpp
    src/tools/drawAppIcon.cpp
    src/controllers/PingControllers.cpp
    src/models/NetworkScanningModel.cpp
    src/models/PingModel.cpp
    src/tools/getLocalIPAddress.cpp
    src/tools/getLocalNetmask.cpp
)